include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/models/**
    - lib/*.g.dart
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  plugins:
    - custom_lint

# custom_lint:
#   rules:
#     - riverpod_provider_dependencies: false