name: adsats_amplify_gen_2
description: "ADSATS - Aviation Document Storage and Tracking System"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  amplify_api: ^2.0.0
  amplify_storage_s3: ^2.0.0
  provider: ^6.1.2
  go_router: ^17.0.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  data_table_2: ^2.5.15
  intl: ^0.20.2
  file_picker: ^10.1.1
  badges: ^3.1.2
  gap: ^3.0.1
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^4.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  collection: ^1.19.1
  flutter_hooks: ^0.21.2
  riverpod: ^3.0.0-dev.17
  hooks_riverpod: ^3.0.0-dev.17
  flutter_multi_select_items: ^0.4.3
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.4.14
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0-dev.17
  go_router_builder: ^4.0.1
  freezed: ^3.0.3
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ADSATS_logo.svg
    - assets/svg/
    - assets/svg/ADSATS_logo.svg
