name: adsats_amplify_gen_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  amplify_api: ^2.0.0
  amplify_storage_s3: ^2.0.0
  url_strategy: ^0.3.0
  provider: ^6.1.2
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  data_table_2: ^2.5.15
  multi_select_flutter: ^4.1.3
  intl: ^0.19.0
  file_picker: ^8.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ADSATS_logo.svg
    - assets/svg/
    - assets/svg/ADSATS_logo.svg
